# permissions for end users to view dfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dfs-operator
    app.kubernetes.io/managed-by: kustomize
  name: dfs-viewer-role
rules:
- apiGroups:
  - storage.cirglo.com
  resources:
  - dfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.cirglo.com
  resources:
  - dfs/status
  verbs:
  - get
