# permissions for end users to edit dfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dfs-operator
    app.kubernetes.io/managed-by: kustomize
  name: dfs-editor-role
rules:
- apiGroups:
  - storage.cirglo.com
  resources:
  - dfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.cirglo.com
  resources:
  - dfs/status
  verbs:
  - get
