---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - storage.cirglo.com
  resources:
  - deployments
  - dfs
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.cirglo.com
  resources:
  - dfs/finalizers
  verbs:
  - update
- apiGroups:
  - storage.cirglo.com
  resources:
  - dfs/status
  verbs:
  - get
  - patch
  - update
